# Docker Compose version
version: "3.6"

services:
  # Main web application service
  app:
    build: ./app
    restart: unless-stopped
    # Map container port 80 to host port 12001
    ports:
      - "12001:80"
    # Mount volumes for persistent storage and development
    volumes:
      - ./app/src:/var/www/html  # Mount source code
    # Environment variables for database connection
    environment:
      # These password and stuff is not neccesarry too secret
      - MYSQL_HOSTNAME=db
      - MYSQL_ROOT_PASSWORD=45299417d86f231f6a584d1488edb763
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
  
  # MySQL database service
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: unless-stopped
    # Expose MySQL port internally only
    expose:
      - 3306
    # Database credentials
    environment:
      # These password and stuff is not neccesarry too secret
      - MYSQL_ROOT_PASSWORD=45299417d86f231f6a584d1488edb763
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password


